### ISSUE TITLE
Enabling vehicles to be loaded up by any items selected. (Food, Fuel, Ammo, etc.)

### ISSUE THREAD

**Issue by NinjaSiren** [NinjaSiren/Yes-Vehicles-finally#10]
Making new assembly files for loading up items the player selected to put inside a vehicle into its inventory.

**Comment by Taranchuk** [comment]
What would it look like? Gizmo on selected items with command move to vehicle?

**Comment by Taranchuk** [comment]
Made in pull request.

**Comment by NinjaSiren** [comment]
Like a menu or something that where you can add specific items needed for a
vehicle.

**Comment by NinjaSiren** [comment]
> Made in pull request.

Something like that on the pull request. It might not be perfect but its ok.

**Comment by NinjaSiren** [comment]
what mods do you use and in what order? I have a possible mod incompatibility. Where the vehicle does not reload, nor show the reload gui.

**Comment by Taranchuk** [comment]
Do you mean CE ammo gizmos? My mods: https://pastebin.com/sdZdHc6X

**Comment by NinjaSiren** [comment]
> Do you mean CE ammo gizmos? My mods: https://pastebin.com/sdZdHc6X

yes, the reload gizmo and weapon ammo gizmo went lost, but the item loader is ok (new game and old save), I think the CE patch? CE:FE updated. I can't reload the weapon.

I am not sure, but the things I did update after the thing went missing is updated the mod for the new patch and updated CE.
