### ISSUE TITLE
To release to Steam Workshop.

### ISSUE THREAD

**Issue by NinjaSiren** [NinjaSiren/Yes-Vehicles-finally#24]
I cannot post this mod in Steam Workshop, because I am using both a non-steam version and pirated version of the game.

**Comment by Taranchuk** [comment]
I don’t have Steam either, so I can’t help.

**Comment by NinjaSiren** [comment]
Oh, well...

**Comment by Taranchuk** [comment]
> I am using both a non-steam version

Have you bought DRM free version? You can get the Steam key for this version. https://rimworldgame.com/getmygame/

**Comment by NinjaSiren** [comment]
There is DRM but not Steam. I might just buy it again but via Steam when I have enough money again to buy it.
