### ISSUE TITLE
Replace "Draft/Undraft" gizmo button with "Start/Stop Engine" text and graphics

### ISSUE THREAD

**Issue by sumghai** [NinjaSiren/Yes-Vehicles-finally#25]
As of v0.8b2 Patch 2, all vehicles still use the pawnlike "Draft/Undraft" gizmo button, which is a bit jarring considering that vehicles are more-or-less non-sentient unless there is a driver.

Perhaps this is an issue with the O21 Vehicles Framework, but would it be possible to override the current "Draft/Undraft" button with "Start/Stop Engine" text and graphics?

(For the record, I've made and customized gizmo buttons for my own Replimat mod, and overridden vanilla game **methods**, but I haven't tried to see if it is possible to also override gizmos)

**Comment by NinjaSiren** [comment]
Oh the draft/undraft is not on my side to be fixed but on the Vehicle Framework. Every vehicle framework mod has this draft/undraft thingy.

And it is based on the framework's pawns based on colonist pawns.

But I will see if is there any way to fix this in any way.

**Comment by sumghai** [comment]
Yes, I suspected this has to do with the Vehicles Framework. Might be best for me to submit this their issue tracker instead, so that they can assess this feature suggestion on their end.
