### ISSUE TITLE
Why do we need APCPack, ATVPack, CartPack, TankPack, TruckPack textures?

### ISSUE THREAD

**Issue by Taranchuk** [NinjaSiren/Yes-Vehicles-finally#28]
I did not find their application anywhere in the xml files.

**Comment by NinjaSiren** [comment]
When I was testing the mod when I added the Raids & Caravans patch, the game keeps giving me red errors about these "pack" textures not found in the texture folder. 

Even though I know that I coded it that it will use the one without the "pack" name.

Kinda weird bug, I don't know if its fixed yet, I am not keen on testing it because when I added the "pack" textures, the mod just works.

**Comment by Taranchuk** [comment]
I think I figured it out. You designate races of vehicles as <packAnimal>true</packAnimal>. After this modification, the game will require these textures. In fact, these texturess are just saddles for animals that appear when they are loaded. You add these textures as yet another vehicles, not as saddles.

**Comment by NinjaSiren** [comment]
> I think I figured it out. You designate races of vehicles as true. After this modification, the game will require these textures. In fact, these texturess are just saddles for animals that appear when they are loaded. You add these textures as yet another vehicles, not as saddles.

Saddles? so it is connected to Giddy-up?

**Comment by Taranchuk** [comment]
![WargPack_south](https://user-images.githubusercontent.com/24846741/73594624-a0f27f80-4518-11ea-93a2-0b7c8c45c002.png)
Well look. This is what you see when the caravan enters the map.

**Comment by NinjaSiren** [comment]
so thats the pack textures. so I just added another layer of vehicle.

**Comment by NinjaSiren** [comment]
anyways its not that of a major thing, it will still look like the vehicle.

**Comment by Taranchuk** [comment]
Well, all texture packs occupy a size of 9 mb, they need to be reduced if they do not play a special role.

**Comment by NinjaSiren** [comment]
ill reduce it to a transparent blank png.

**Comment by Taranchuk** [comment]
Problem solved.
