### ISSUE TITLE
Adding AI support?

### ISSUE THREAD

**Issue by TheEventHorizon** [NinjaSiren/Yes-Vehicles-finally#3]
Would it be difficult for raids/enemy bases to utilize vehicles?

**Comment by NinjaSiren** [comment]
I will include that in the near future, with possibly Rimsenal and
Polarisbloc mods compatibility.

Then possibly include compatibility for WhatTheHack! mod for enemy vehicle
capturing.

Thank you for the reply.

**Comment by NinjaSiren** [comment]
v0.7c has added base game AI factions raids/bases/caravans vehicles. 

I'll add minor tweaks on it.
