### ISSUE TITLE
[question] [bug?] Are the Vehicle Weapons designed to be equiped by pawns?

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [NinjaSiren/Yes-Vehicles-finally#9]
I recently accidentally equipped one of my pawns with a machine gun instead of installing it on to a truck. With this, I was also unable to unequip said machine gun and had to revert to an autosave. I went on to a test world and also discovered this is reproducible with all the other vehicle weapons.

Ver. 1.0
Mod Loading Order:
1. BetterLoading
2. Core
3. Hugslib
4. JecsTools
5. [O21] Vehicle Framework
6. All Other Mods
7. Yes, Vehicles, finally

**Comment by NinjaSiren** [comment]
Oh, on my idea no, but this is almost impossible to fix yet. As this will change alot of codes and codes from the dependencies, especially [O21] Vehicle Framework. 

Plus, maybe its a feature? XD

**Comment by PaxiTheAlchemist** [comment]
Hmm... Interesting to hear. I have a suggestion, maybe you can make it into an actual feature. Possibly have it so that when not equiped on a vehicle the weapon will have a negative offset, preferably an accuracy and walk speed decrease and maybe even global work speed decrease aswell? I also would like to add possibly fixing the inability to unequip the weapons as well?  I've never coded a mod for Rimworld or any game in general so I say this without experience, however, if you could actually make this into a feature, that would be awesome (and not buggy and over powered)

**Comment by NinjaSiren** [comment]
Sure, Ill add that to my list of pending works. I have been playing Azur Lane lately so, pawns with big guns.
